/* generated by the admin card - public Firebase web config + project name (no passwords) */
window.DPB_FIREBASE_CONFIG = {"apiKey":"AIzaSyCRK-WkEHOfmxlSIhz4SnZTt2QV-A33gjQ","authDomain":"solar-productivity.firebaseapp.com","projectId":"solar-productivity","storageBucket":"solar-productivity.firebasestorage.app","messagingSenderId":"578093863","appId":"1:578093863:web:ab87b23d96005b8c0d1f02"};
window.DPB_FIREBASE_NS = "test";
